version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=3 drip_backend.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      # This value of the secret key will need to change for the user
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin4:
    image: dpage/pgadmin4:5.0
    depends_on:
      - db
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "80:80"

volumes:
  postgres_data: