version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=3 django_website.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=
      - DEBUG=0
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11