version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=3 drip_backend.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      # This value of the secret key will need to change for the user
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: